version: '3.7'

services:
  db:    
    build: ./MariaDB/
    user: "1000"    
    container_name: db   
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: my_database
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes: 
        - "./db_vol:/var/lib/mysql"
        - "./log/db:/var/log"
    networks:
      front:
        ipv4_address: 172.16.202.2        

  phpmyadmin:    
    image: phpmyadmin 
    container_name: phpmyadmin   
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRAY=1
    networks:
      front:
        ipv4_address: 172.16.202.3

  web:      
    build: .
    user: "1000"
    container_name: php
    ports:
    - "80:80"
    tty: true
    volumes: 
      - "../Restaurant:/var/www"
      - "./log/apache:/var/log/apache2"
      - "./log/php:/var/log"
    networks:
      front:
        ipv4_address: 172.16.202.4
      
  mailer:
    container_name: mailer
    image: schickling/mailcatcher
    ports:
    - "1025:25"
    - "1080:1080"
    networks:
      front:
        ipv4_address: 172.16.202.6

networks:
  front:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.202.0/24    
