version: '3'
services:
  db:    
    build: ./MariaDB/
    user: "1000"    
    container_name: db   
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: my_database
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes: 
        - "./db_vol:/var/lib/mysql"
        - "./log/db:/var/log"        

  phpmyadmin:    
    image: phpmyadmin 
    container_name: phpmyadmin   
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRAY=1

  web:      
      build: .
      user: "1000"
      container_name: php
      ports:
      - "80:80"
      tty: true
      volumes: 
        - "../Restaurant:/var/www"
        - "./log/apache:/var/log/apache2"
        - "./log/php:/var/log"

  mailer:
    container_name: mailer
    image: schickling/mailcatcher
    ports:
    - "1025:1025"
    - "1080:1080"    
